server:
  port: 9031
spring:
  application:
    name: eureka-pro
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
application:
  server:
    token:
      api: eureka-pro
      rest: eureka-pro