package com.bitprogress.exception;

/**
 * @author wuwuwupx
 *  定时任务异常错误码
 */
public class ScheduleErrorCodes {

    public static final String QUARTZJOB_CREATE_EXCEPTION_CODE = "QUARTZJOB_CREATE_EXCEPTION";
    public static final String QUARTZJOB_NAME_EMPTY_EXCEPTION_CODE = "QUARTZJOB_NAME_EMPTY_EXCEPTION";
    public static final String QUARTZJOB_CRON_EMPTY_EXCEPTION_CODE = "QUARTZJOB_CRON_EMPTY_EXCEPTION";
    public static final String QUARTZJOB_TYPE_EMPTY_EXCEPTION_CODE = "QUARTZJOB_TYPE_EMPTY_EXCEPTION";
    public static final String QUARTZJOB_QUERY_EXCEPTION_CODE = "QUARTZJOB_QUERY_EXCEPTION";
    public static final String QUARTZJOB_REMOVE_EXCEPTION_CODE = "QUARTZJOB_REMOVE_EXCEPTION";
    public static final String QUARTZJOB_CHECK_EXISTS_EXCEPTION_CODE = "QUARTZJOB_CHECK_EXISTS_EXCEPTION";
    public static final String JOBKEY_QUERY_EXCEPTION_CODE = "JOBKEY_QUERY_EXCEPTION";
    public static final String TRIGGER_PAUSE_EXCEPTION_CODE = "TRIGGER_PAUSE_EXCEPTION";
    public static final String TRIGGER_RESCHEDULE_EXCEPTION_CODE = "TRIGGER_RESCHEDULE_EXCEPTION";
    public static final String JOBGROUP_QUERY_EXCEPTION_CODE = "JOBGROUP_QUERY_EXCEPTION";

    public static final String GROUP_NOT_EXIST_EXCEPTION_CODE = "GROUP_NOT_EXIST";
    public static final String GROUP_SAVE_EXCEPTION_CODE = "GROUP_SAVE_EXCEPTION";
    public static final String GROUP_UPDATE_EXCEPTION_CODE = "GROUP_UPDATE_EXCEPTION";
    public static final String GROUP_DELETE_EXCEPTION_CODE = "GROUP_DELETE_EXCEPTION";
    public static final String GROUP_IS_ASSIGNED_EXCEPTION_CODE = "GROUP_IS_ASSIGNED_EXCEPTION";

    public static final String QUARTZJOB_NOT_EXIST_EXCEPTION_CODE = "QUARTZJOB_NOT_EXIST";
    public static final String QUARTZJOB_SAVE_EXCEPTION_CODE = "QUARTZJOB_SAVE_EXCEPTION";
    public static final String QUARTZJOB_UPDATE_EXCEPTION_CODE = "QUARTZJOB_UPDATE_EXCEPTION";
    public static final String QUARTZJOB_DELETE_EXCEPTION_CODE = "QUARTZJOB_DELETE_EXCEPTION";
    public static final String QUARTZJOB_CRON_INVALID_EXCEPTION_CODE = "QUARTZJOB_CRON_INVALID_EXCEPTION";
    public static final String QUARTZJOB_DURATION_IS_NULL_EXCEPTION_CODE = "QUARTZJOB_DURATION_IS_NULL_EXCEPTION";
    public static final String QUARTZJOB_GET_TRIGGER_STATE_EXCEPTION_CODE = "QUARTZJOB_GET_TRIGGER_STATE_EXCEPTION";

}
