package com.bitprogress.exception;

/**
 * @author wuwuwupx
 * 基础模块错误码
 */
public class BaseErrorCodes {

    public static final String USER_NOT_EXIST_EXCEPTION_CODE = "USER_NOT_EXIST";
    public static final String USER_SAVE_EXCEPTION_CODE = "USER_SAVE_EXCEPTION";
    public static final String USER_UPDATE_EXCEPTION_CODE = "USER_UPDATE_EXCEPTION";
    public static final String USER_DELETE_EXCEPTION_CODE = "USER_DELETE_EXCEPTION";

    public static final String NOT_ROOT_EDIT_OTHER_INFO_CODE = "NOT_ROOT_EDIT_OTHER_INFO";
    public static final String NOT_ROOT_CHECK_OTHER_INFO_CODE = "NOT_ROOT_CHECK_OTHER_INFO";
    public static final String ALLOW_ADD_WPX_EXCEPT_ROOT_CODE = "NOT_ALLOW_ADD_WPX_EXCEPT_ROOT";
    public static final String MANAGER_NOT_EXIST_CODE = "MANAGER_NOT_EXIST";
    public static final String MANAGER_UPDATE_EXCEPTION_CODE = "MANAGER_UPDATE_EXCEPTION";
    public static final String MANAGER_DELETE_EXCEPTION_CODE = "MANAGER_DELETE_EXCEPTION";
    public static final String MANAGER_SAVE_EXCEPTION_CODE = "MANAGER_SAVE_EXCEPTION";
    public static final String ROOT_DELETE_EXCEPTION_CODE = "ROOT_CANNOT_DELETE";
    public static final String NOT_ROOT_CANNOT_DELETE_CODE = "NOT_ROOT_CANNOT_DELETE";
    public static final String ROOT_CANNOT_DISABLED_CODE = "ROOT_CANNOT_DISABLED";
    public static final String NOT_ROOT_CANNOT_DISABLED_CODE = "NOT_ROOT_CANNOT_DISABLED";
    public static final String NOT_ALLOW_SUPERIOR_ROLE_CODE = "NOT_ALLOW_SUPERIOR_ROLE";

    public static final String APP_NOT_EXIST_EXCEPTION_CODE = "APP_NOT_EXIST";
    public static final String APP_SAVE_EXCEPTION_CODE = "APP_SAVE_EXCEPTION";
    public static final String APP_UPDATE_EXCEPTION_CODE = "APP_UPDATE_EXCEPTION";
    public static final String APP_DELETE_EXCEPTION_CODE = "APP_DELETE_EXCEPTION";

    public static final String WECHATUSER_NOT_EXIST_EXCEPTION_CODE = "WECHATUSER_NOT_EXIST";
    public static final String WECHATUSER_SAVE_EXCEPTION_CODE = "WECHATUSER_SAVE_EXCEPTION_CODE";
    public static final String WECHATUSER_UPDATE_EXCEPTION_CODE = "WECHATUSER_UPDATE_EXCEPTION";
    public static final String WECHATUSER_DELETE_EXCEPTION_CODE = "WECHATUSER_DELETE_EXCEPTION";
    public static final String WECHATAPPLETUSER_NOT_EXIST_EXCEPTION_CODE = "WECHATAPPLETUSER_NOT_EXIST";
    public static final String WECHATAPPLETUSER_SAVE_EXCEPTION_CODE = "WECHATAPPLETUSER_SAVE_EXCEPTION";
    public static final String WECHATAPPLETUSER_UPDATE_EXCEPTION_CODE = "WECHATAPPLETUSER_UPDATE_EXCEPTION";
    public static final String WECHATAPPLETUSER_DELETE_EXCEPTION_CODE = "WECHATAPPLETUSER_DELETE_EXCEPTION";
    public static final String WECHATOAUSER_NOT_EXIST_EXCEPTION_CODE = "WECHATOAUSER_NOT_EXIST";
    public static final String WECHATOAUSER_SAVE_EXCEPTION_CODE = "WECHATOAUSER_SAVE_EXCEPTION";
    public static final String WECHATOAUSER_UPDATE_EXCEPTION_CODE = "WECHATOAUSER_UPDATE_EXCEPTION";
    public static final String WECHATOAUSER_DELETE_EXCEPTION_CODE = "WECHATOAUSER_DELETE_EXCEPTION";
    public static final String WECHATAPP_NOT_EXIST_EXCEPTION_CODE = "WECHATAPP_NOT_EXIST";
    public static final String WECHATAPP_SAVE_EXCEPTION_CODE = "WECHATAPP_SAVE_EXCEPTION";
    public static final String WECHATAPP_UPDATE_EXCEPTION_CODE = "WECHATAPP_UPDATE_EXCEPTION";
    public static final String WECHATAPP_DELETE_EXCEPTION_CODE = "WECHATAPP_DELETE_EXCEPTION";
    public static final String UNION_ID_EMPTY_EXCEPTION_CODE = "UNION_ID_EMPTY_EXCEPTION";
    public static final String OPENID_ID_EMPTY_EXCEPTION_CODE = "OPENID_ID_EMPTY_EXCEPTION";
    public static final String NOT_WECHATUSER_EXCEPTION_CODE = "NOT_WECHATUSER_EXCEPTION";
    public static final String REFRESH_ACCESSTOKEN_EXCEPTION_CODE = "REFRESH_ACCESSTOKEN_EXCEPTION";

    public static final String PHONEUSER_NOT_EXIST_EXCEPTION_CODE = "PHONEUSER_NOT_EXIST";
    public static final String PHONEUSER_SAVE_EXCEPTION_CODE = "PHONEUSER_SAVE_EXCEPTION";
    public static final String PHONEUSER_UPDATE_EXCEPTION_CODE = "PHONEUSER_UPDATE_EXCEPTION";
    public static final String PHONEUSER_DELETE_EXCEPTION_CODE = "PHONEUSER_DELETE_EXCEPTION";

}
